### ISSUE TITLE
Collaborate on bugcontrol-boogdroid (and bugdroid)

### ISSUE THREAD

**Issue by albfan** [jonanp/BugsControl#17]
Hi, I guess we can talk in spanish but anyway...

I have been working on a fork from your repo (adding xmlrpc support) which is the avaliable api for gnome bugzilla, and easing navigation adding filterable list.

Now I want to add edit features

https://github.com/JohnMHarrisJr/BoogDroid/issues/9

Do you want to collaborate or provide some ideas or analysis?  I see you have a bunch of open issues related with edit, add comments and some bugs we all can get rid of.

Rebase your master if you want and publish to google play if you want.

I have talked with maintainer of bugdroid, who implement the rest api for bugzilla, and I will integrate it too on this app.

**Comment by jonan** [comment]
Wow, really nice to see someone taking over my work. I didn't know anyone was working on this.

I don't have much time to dedicate to this project anymore, but I'll try to keep an eye on the development and collaborate whenever I can.

**Comment by albfan** [comment]
What about publish on google play? It has the add coment feature implemented and in next days the change status. Want to receive a ready PR?

**Comment by jonan** [comment]
BoogDroid is already in the Play Store, why do you want BugsControl there too?

**Comment by albfan** [comment]
Current maintainer is against google play drm policy and requested a delete for it. I can publish it but prefer to ask first existing apps. I think you have it deployed there, my mistake. Then keep and eye on our repo, any help is appreciated.
